Added base Profile API stuff
LifeIsAParadox/Skyblocker pull request #48
Opened 2022-02-23 22:04 UTC by TacoMonkey11

just the actual records and stuff to hold the data, not the profile viewer

I've spent way too much time just doing the records, and I don't feel like making a GUI right now...

Marked as a draft because I still may add some extra utils

2022-03-01 14:18 UTC, ExternalTime commented
Have you considered not nesting all player profile data inside single class? IMO it hurts readability.

2022-03-01 15:25 UTC, TacoMonkey11 commented
Yeah I’ve considered it, I guess I never really noticed it because I hust collapsed

2022-03-05 13:48 UTC, KonaeAkira requested changes

2022-03-05 13:48 UTC, KonaeAkira commented on src/main/java/me/xmrvizzy/skyblocker/skyblock/api/ProfileUtils.java
> +        } catch (IOException e) {
Since we're not doing anything special with the exceptions, maybe use `Exception` instead of `IOException`? Would catch all other unexpected things.

2022-03-05 13:48 UTC, KonaeAkira commented on src/main/java/me/xmrvizzy/skyblocker/skyblock/api/ProfileUtils.java
> +            } catch (IOException e) {
Same here. Replace `IOException` with `Exception`.

2022-03-05 14:31 UTC, KonaeAkira approved these changes

2022-03-05 14:32 UTC, merged